apiVersion: v1
kind: ConfigMap
metadata:
  name: tt3y5d-secret
  namespace: tt3y5d
data:
  HTTP_OR_SSL: http://
  DOMAIN: 192-168-1-200.nip.io
  DB_NAME: refurb
  DB_PASS: refurb
  DB_USER: refurb
  APP_ENV: prod
  DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@tt3y5d-db/${DB_NAME}
  POSTGRES_DB: ${DB_NAME}
  POSTGRES_PASSWORD: ${DB_PASS}
  POSTGRES_USER: ${DB_USER}
  CORS_ALLOW_ORIGIN: ^${HTTP_OR_SSL}${DOMAIN}$$
  TRUSTED_HOSTS: ^(www\.)?${DOMAIN}$$
