apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt3y5d-api
  labels:
    app: tt3y5d-api
  namespace: tt3y5d
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tt3y5d-api
  template:
    metadata:
      labels:
        app: tt3y5d-api
    spec:
      containers:
        - name: tt3y5d-php
          image: tt3y5d-php
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: tt3y5d-secret
          volumeMounts:
            - name: php-storage
              mountPath: /srv/api
        - name: tt3y5d-api
          image: tt3y5d-api
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: tt3y5d-secret
          volumeMounts:
            - name: php-volume
              mountPath: /srv/api
            - name: api-volume
              mountPath: /srv/api/public
            - name: nginx-volume
              mountPath: /etc/nginx/conf.d/default.conf
      volumes:
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: nginx-storage-pvc
        - name: api-volume
          persistentVolumeClaim:
            claimName: api-storage-pvc
        - name: php-volume
          persistentVolumeClaim:
            claimName: php-storage-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt3y5d-db
  labels:
    app: tt3y5d-db
  namespace: tt3y5d
spec:
  selector:
    matchLabels:
      app: tt3y5d-db
  template:
    metadata:
      labels:
        app: tt3y5d-db
    spec:
      containers:
        - name: tt3y5d-db
          image: postgres:9.6-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: tt3y5d-secret
