kind: Namespace
apiVersion: v1
metadata:
  name: tt3y5d
  labels:
    name: tt3y5d
---
kind: Service
apiVersion: v1
metadata:
  name: tt3y5d-api
  namespace: tt3y5d
spec:
  ports:
    - port: 80
      name: web
      protocol: TCP
  selector:
    app: tt3y5d-api
---
kind: Service
apiVersion: v1
metadata:
  name: tt3y5d-db
  namespace: tt3y5d
spec:
  ports:
    - port: 5432
      name: web
      protocol: TCP
  selector:
    app: tt3y5d-db
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tt3y5d
  namespace: tt3y5d
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`192.168.1.200`) && PathPrefix(`/`)
      services:
        - name: tt3y5d-api
          port: 80
