apiVersion: v1
kind: ConfigMap
metadata:
  name: tt3y5d-secret
  namespace: tt3y5d
data:
  HTTP_OR_SSL: http://
  DOMAIN: 192-168-1-200.nip.io
  DB_NAME: refurb
  DB_PASS: refurb
  DB_USER: refurb
  APP_ENV: prod
  DATABASE_URL: postgres://refurb:refurb@tt3y5d-db/refurb
  POSTGRES_DB: refurb
  POSTGRES_PASSWORD: refurb
  POSTGRES_USER: refurb
  CORS_ALLOW_ORIGIN: ^$(HTTP_OR_SSL)$(DOMAIN)$$
  TRUSTED_HOSTS: ^(www\.)?$(DOMAIN)$$
