apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt3y5d
  labels:
    app: tt3y5d
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tt3y5d
  template:
    metadata:
      labels:
        app: tt3y5d
    spec:
      containers:
        - name: tt3y5d-php
          image: tt3y5d-php
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: tt3y5d-secret
        - name: tt3y5d-api
          image: tt3y5d-api
          imagePullPolicy: Never
          ports:
            - containerPort: 80
        - name: tt3y5d-db
          image: postgres:9.6-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: tt3y5d-secret
