#index:
#    path: /
#    controller: App\Controller\DefaultController::index

welcome:
  path: /
  controller: App\Controller\App::welcome

certificates:
  path: /certificates
  controller: App\Controller\App::certificates

certificatesPDF:
  path: /certificates/generator
  methods: [POST]
  controller: App\Controller\App::certificatesPDF
