#index:
#    path: /
#    controller: App\Controller\DefaultController::index

welcome:
  path: /
  controller: App\Controller\Welcome

certificates:
  path: /certificates
  controller: App\Controller\Certificate::certificates

certificatesPDF:
  path: /certificates/generator
  methods: [POST]
  controller: App\Controller\Certificate::certificatesPDF

orders:
  path: /orders
  controller: App\Controller\Orders::orders

ordersPDF:
  path: /orders/generator
  methods: [POST]
  controller: App\Controller\Orders::ordersPDF
